COMMON: &common #标识
  DEBUG: False

  # 日志配置文件路径
  LOGGING_CONFIG_PATH: ./config/logging.yaml
  # 日志文件存放位置
  LOGGING_PATH: ./logs

  # 上传文件的存储位置
  UPLOAD_FOLDER: uploads
  # 预设文件的存储位置
  ASSET_FOLDER: assets

  # flask秘钥
  SECRET_KEY: zheshiyiduanhenfuzadezifuchuan

  # Flask_login的session设置
  SESSION_COOKIE_HTTPONLY: False  # 使cookie可以被访问

DEVELOPMENT: &development
  <<: *common # 继承common，没有重新定义的变量，使用common变量值
  DEBUG: True

  # 数据库连接
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:1233lgz@localhost:3307/db'
  SQLALCHEMY_TRACK_MODIFICATIONS: False

PRODUCTION: &production
  <<: *common

  # 数据库连接
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:1233lgz@localhost:3306/db'
  SQLALCHEMY_TRACK_MODIFICATIONS: False