version: 1
disable_existing_loggers: False
# 定义日志输出格式，可以有多种格式输出
formatters:
  simple:
      format: "%(asctime)s [%(pathname)s] [%(funcName)s] [%(levelname)s] %(message)s"
  error:
      format: "%(asctime)s [%(pathname)s] [%(funcName)s] [%(levelname)s] %(message)s"

# 定义不同的handler，输出不同等级的日志消息
handlers:
  console:
      class: logging.StreamHandler # 输出到控制台
      level: DEBUG
      formatter: simple
      stream: ext://flask.logging.wsgi_errors_stream # 监听flask日志
  info_file_handler:
      class: logging.handlers.RotatingFileHandler # 输出到文件
      level: INFO
      formatter: simple
      filename: ./logs/info.log
      maxBytes: 10485760 # 10MB
      backupCount: 10 #most 10 extensions
      encoding: utf8
  error_file_handler:
      class: logging.handlers.RotatingFileHandler # 输出到文件
      level: ERROR
      formatter: error
      filename: ./logs/errors.log
      maxBytes: 10485760 # 10MB
      backupCount: 10
      encoding: utf8
# 启用handler
root:
  level: INFO
  handlers: [console,info_file_handler,error_file_handler]